repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.5
    hooks:
      # Run the linter.
      - id: ruff
        # args: [ --fix ]

      # Run the formatter.
      - id: ruff-format
        args: [ --check, --diff ]
