# --- Build System -------------------------------------------------------------
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

# --- Project Metadata ---------------------------------------------------------
[project]
name = "nutree"
dynamic = ["version"]
description = "A Python library for tree data structures with an intuitive, yet powerful, API."
readme = "README.md"
license = {file = "LICENSE.txt"}
authors = [
    {name = "Martin Wendt", email = "nutree@wwwendt.de"},
]
maintainers = [
    {name = "Martin Wendt", email = "nutree@wwwendt.de"},
]
keywords = ["tree", "data structure", "digraph", "graph", "nodes", "hierarchy", "treelib"]
classifiers = [
    # "Development Status :: 3 - Alpha",
    # "Development Status :: 4 - Beta",
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    # "Programming Language :: Python :: 3.7  # EOL 2023-06-27",
    # "Programming Language :: Python :: 3.8  # EOL 2024-10",
    # "Programming Language :: Python :: 3.9", # EOL 2025-10
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
dependencies = [
    "typing_extensions>=4.0",
]

[project.optional-dependencies]
graph = ["pydot", "rdflib", "graphviz"]
random = ["fabulist"]
all = ["pydot", "rdflib", "graphviz", "fabulist"]

[tool.uv.sources]
benchman = {path = "../benchman", editable = true}

[dependency-groups]
dev = [
    "benchman",
    "fabulist",
    "ipykernel",
    "lxml",
    "mypy",
    "notebook",
    "pre-commit",
    "pydot",
    "pyright",
    "pytest",
    "pytest-cov",
    "pytest-html",
    "PyYAML",
    "rdflib",
    "ruff>=0.9",
    "setuptools>=42",
    "Sphinx",
    "furo",
    "myst-parser[linkify]",
    "sphinxcontrib-googleanalytics",
    "sphinxcontrib-mermaid",
    "sphinx-rtd-theme",
    "tox",
    "tox-uv",
    "twine",
    "yabs",
]

[project.urls]
Homepage = "https://github.com/mar10/nutree/"
"Bug Tracker" = "https://github.com/mar10/nutree/issues"
"Source Code" = "https://github.com/mar10/nutree"
Documentation = "https://nutree.readthedocs.io/"
Download = "https://github.com/mar10/nutree/releases/latest"

# --- Setuptools Configuration -------------------------------------------------
# [tool.setuptools.dynamic]
# version = {attr = "nutree.__version__"}

# [tool.setuptools.packages.find]
# where = ["."]
# exclude = ["tests*"]

# [tool.setuptools.package-data]
# nutree = ["py.typed"]


# --- Ruff Settings ------------------------------------------------------------
[tool.ruff]
target-version = "py310"
src = ["nutree", "tests"]
select = [
  "B",  # bugbear
  # "D",   # pydocstyle
  "E",  # pycodestyle
  "F",  # pyflakes
  "G",  # flake8-logging-format
  "I",  # isort
  "T",  # print, ...
  "UP", # pyupgrade
]
ignore = [
  # # We need the old syntax for python <= 3.9
  # "UP006", # Use `list` instead of `List` for type annotations (since Py39)
  # "UP007", # Use `X | Y` for type annotations (since Py310)
  "E721",  #  Do not compare types, use `isinstance()`
]

[tool.ruff.per-file-ignores]
# Jupyter Notebooks
"*.ipynb" = [
  "T20",  # print statement
  "E402",  # module level import not at top of file
]

# [tool.ruff.isort]
# case-sensitive = true

# [tool.ruff.pydocstyle]
# convention = "google"

# --- Pyright Settings ---------------------------------------------------------
[tool.pyright]
typeCheckingMode = "standard"
include = ["nutree", "tests"]
reportMissingImports = "none"
deprecateTypingAliases = true

# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file
reportUnnecessaryTypeIgnoreComment = true

# executionEnvironments = [
#   { root = "nutree", typeCheckingMode = "strict" },
#   { root = "tests", typeCheckingMode = "standard", reportUnnecessaryTypeIgnoreComment = false },
# ]



# --- Mypy Settings ------------------------------------------------------------
[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
warn_unused_ignores = true
# warn_redundant_casts = true
# ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
  "fabulist",
  "pydot",
  "pytest",
  "pympler",
  "pympler.asizeof",
  "rdflib",
  "rdflib.namespace",
  "typing_extensions",
]
ignore_missing_imports = true

# --- Pytest and Coverage Settings ---------------------------------------------
[tool.pytest.ini_options]
# addopts = "-ra -q --cov=nutree --cov-report=html"
addopts = "-ra -q --cov=nutree"
# addopts = "--cov=nutree --cov-report=html --cov-report=term-missing"

markers = [
    "benchmarks: include slow benchmarks (enable with '-m benchmarks')",
    # "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    # "serial",
]

[tool.coverage.run]
# branch = true
omit = [
    "tests/*",
    "setup.py",
    # nutree/leaves_cli.py
    # nutree/cli_common.py
    # nutree/monitor/*  
]

[tool.coverage.report]
precision = 1
# show_missing = true
sort = "Name"
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
exclude_also = [
    # 1. Exclude an except clause of a specific form:
    # "except ValueError:\\n\\s*assume\\(False\\)",
    # 2. Comments to turn coverage on and off:
    # "no cover: start(?s:.)*?no cover: stop",
    # 3. A pragma comment that excludes an entire file:
    # "\\A(?s:.*# pragma: exclude file.*)\\Z",
    "\\A(?s:.*# pragma: exclude-file-from-coverage.*)\\Z",
    ]

[tool.coverage.html]
directory = "build/coverage"

